### ISSUE TITLE
LaTeX Error: File `clearpath-latex/clearpath-manual.cls' not found

### ISSUE THREAD

**Issue by MengGuo** [jackal/jackal-user-manual#12]
the following error appears after clone and xelatex:

``` LaTeX Error: File `clearpath-latex/clearpath-manual.cls' not found.```

**Comment by tonybaltovski** [comment]
Did you check out the submodule when cloning?

**Comment by MengGuo** [comment]
Just saw that. Then you guys should modify the Readme as it is not just "Xelatex"...

**Comment by tonybaltovski** [comment]
Cloning recursively will pull the submodule but I agree the README should capture that.  I'll bring your concern up with our Marketing team, they control the assets on our main website.

Were you able to build it successfully?

**Comment by MengGuo** [comment]
Just tried.  Various errors about fonts... then a error about "PNG" vs "png". 

Please see the attached changes. It complies and generates the pdf. 

*changes to ```clearpath-manual.cls```*
- comment out Line 28-31
- comment out Line 57-61

*changes to ```jackal.tex```*
- Line 228, change ".PNG" to ".png".
[jackal.pdf](https://github.com/jackal/jackal-user-manual/files/1084943/jackal.pdf)
